/* FitTrack Pro v14 — domain catalog. */
(function(){
  const FT=window.FitTrack=window.FitTrack||{};
  const WEEKDAYS=['sun','mon','tue','wed','thu','fri','sat'];
  const WD_LABELS={sun:'Sunday',mon:'Monday',tue:'Tuesday',wed:'Wednesday',thu:'Thursday',fri:'Friday',sat:'Saturday'};
  const MUSCLE_GROUPS=['Chest','Back','Shoulders','Biceps','Triceps','Legs','Glutes','Core','Cardio','Full Body'];
  const SEED_EXERCISES=[
  {name:'Incline Bench Press',   mg:'Chest',    ds:3,dr:'10–12',note:'Tempo 3-1-1, shoulder-safe'},
  {name:'Flat Bench Press',      mg:'Chest',    ds:4,dr:'8–10', note:'Primary chest compound'},
  {name:'Dumbbell Bench Press',  mg:'Chest',    ds:3,dr:'12',   note:'Full stretch at bottom'},
  {name:'Pec Dec',               mg:'Chest',    ds:3,dr:'12–15',note:'Peak contraction squeeze'},
  {name:'Push-up',               mg:'Chest',    ds:3,dr:'12',   note:'Full range, chest to floor'},
  {name:'Skull Crusher',         mg:'Triceps',  ds:3,dr:'12',   note:'EZ bar, elbows in'},
  {name:'Lat Pulldown',          mg:'Back',     ds:3,dr:'10–12',note:'Wide grip, full stretch'},
  {name:'T-Bar Row',             mg:'Back',     ds:3,dr:'10–12',note:'Chest on pad, full range'},
  {name:'Chest Supported Row',   mg:'Back',     ds:3,dr:'10–12',note:'Removes lower back stress'},
  {name:'Straight Arm Pulldown', mg:'Back',     ds:3,dr:'12',   note:'Arms straight, lat isolation'},
  {name:'Seated Cable Row',      mg:'Back',     ds:3,dr:'12',   note:'Retract shoulder blades'},
  {name:'Single Arm DB Row',     mg:'Back',     ds:3,dr:'12',   note:'Keep hips square'},
  {name:'Barbell Row',           mg:'Back',     ds:3,dr:'10–12',note:'Hinge at hips, pull to waist'},
  {name:'Face Pull',             mg:'Shoulders',ds:3,dr:'15',   note:'Shoulder health priority'},
  {name:'Shoulder Press',        mg:'Shoulders',ds:3,dr:'8–10', note:'Dumbbells preferred'},
  {name:'Lateral Raise',         mg:'Shoulders',ds:3,dr:'12–15',note:'Slow 3s eccentric'},
  {name:'Preacher Curl',         mg:'Biceps',   ds:3,dr:'12',   note:'Full range, slow neg'},
  {name:'Barbell Curl',          mg:'Biceps',   ds:3,dr:'10–12',note:'No swinging, strict form'},
  {name:'Incline DB Curl',       mg:'Biceps',   ds:3,dr:'12',   note:'Full stretch for peak'},
  {name:'Hammer Curl',           mg:'Biceps',   ds:3,dr:'12',   note:'Brachialis focus'},
  {name:'Arm Curl (Cable)',       mg:'Biceps',   ds:3,dr:'20',   note:'Light, high rep, squeeze'},
  {name:'Triceps Pushdown',      mg:'Triceps',  ds:3,dr:'12–15',note:'Elbows fixed, squeeze'},
  {name:'Overhead Extension',    mg:'Triceps',  ds:3,dr:'12',   note:'Elbows in, control'},
  {name:'Triceps Rope Pulldown', mg:'Triceps',  ds:3,dr:'12–15',note:'Superset with Face Pull'},
  {name:'Squat',                 mg:'Legs',     ds:3,dr:'10',   note:'Depth below parallel'},
  {name:'Sumo Squat',            mg:'Legs',     ds:3,dr:'8–12', note:'Wide stance, toes 45°'},
  {name:'RDL',                   mg:'Legs',     ds:3,dr:'12',   note:'Hinge, feel hamstring'},
  {name:'Leg Curl',              mg:'Legs',     ds:3,dr:'12',   note:'Full range, slow eccentric'},
  {name:'Leg Press',             mg:'Legs',     ds:3,dr:'12',   note:'Standard width'},
  {name:'Wide Leg Press',        mg:'Legs',     ds:3,dr:'12',   note:'Feet high+wide = glutes'},
  {name:'Leg Extension',         mg:'Legs',     ds:3,dr:'12',   note:'Full extension, squeeze quads'},
  {name:'Lunges',                mg:'Legs',     ds:3,dr:'12',   note:'Walking, DBs 15–20 kg'},
  {name:'Calf Raises',           mg:'Legs',     ds:4,dr:'15',   note:'Full stretch, pause at top'},
  {name:'Tibialis Raise',        mg:'Legs',     ds:3,dr:'15',   note:'Shin strength'},
  {name:'Hip Thrust',            mg:'Glutes',   ds:3,dr:'15',   note:'Smith machine or barbell'},
  {name:'Abs Circuit',           mg:'Core',     ds:1,dr:'10 min',note:'Plank, leg raise, crunch, bicycle'},
  {name:'Plank',                 mg:'Core',     ds:3,dr:'60s',  note:'Maintain neutral spine'},
  {name:'Hanging Leg Raise',     mg:'Core',     ds:3,dr:'15',   note:'Full ROM, slow'},
  {name:'Cable Crunch',          mg:'Core',     ds:3,dr:'15',   note:'Weighted ab work'},
  {name:'Russian Twist',         mg:'Core',     ds:3,dr:'20',   note:'Plate or medicine ball'},
  {name:'Treadmill',             mg:'Cardio',   ds:1,dr:'20 min',note:'Incline 10, speed 4.5–5',isCardio:true},
  {name:'Standalone Cycling',    mg:'Cardio',   ds:1,dr:'5 min', note:'Warm-up, low resistance',isCardio:true},
  {name:'HIIT Treadmill',        mg:'Cardio',   ds:1,dr:'20 min',note:'30s sprint/30s walk ×10',isCardio:true},
  {name:'Rowing Machine',        mg:'Cardio',   ds:1,dr:'15 min',note:'Steady or interval',isCardio:true},
  {name:'Burpees',               mg:'Full Body',ds:3,dr:'10–15',note:'Circuit, full extension'},
  {name:'Jump Squats',           mg:'Full Body',ds:3,dr:'15',   note:'Circuit, land soft'},
  {name:'Kettlebell Swings',     mg:'Full Body',ds:3,dr:'20',   note:'Circuit, hip drive'},
];
  const SEED_PLANS=[
  {name:'Legs — Hamstring Focus',emoji:'🦵',exNames:['Standalone Cycling','Sumo Squat','RDL','Leg Curl','Wide Leg Press','Calf Raises','Treadmill']},
  {name:'Push Day',emoji:'💪',exNames:['Incline Bench Press','Dumbbell Bench Press','Pec Dec','Shoulder Press','Lateral Raise','Triceps Pushdown','Overhead Extension','Push-up','Treadmill']},
  {name:'Pull Day',emoji:'🔙',exNames:['Lat Pulldown','T-Bar Row','Chest Supported Row','Straight Arm Pulldown','Barbell Curl','Incline DB Curl','Hammer Curl','Arm Curl (Cable)','Abs Circuit','Treadmill']},
  {name:'Lower — Quad Focus',emoji:'⬇️',exNames:['Squat','Leg Extension','Leg Press','Lunges','Calf Raises','Tibialis Raise']},
  {name:'Upper Superset Day',emoji:'🏋️',exNames:['Flat Bench Press','Barbell Row','Shoulder Press','Lat Pulldown','Lateral Raise','Preacher Curl','Triceps Rope Pulldown','Face Pull','Abs Circuit','Treadmill']},
  {name:'Full Body HIIT',emoji:'🔥',exNames:['Burpees','Jump Squats','Push-up','Kettlebell Swings','HIIT Treadmill']},
];

// ── FOOD DATABASE — Indian/Nepali ─────
  const FOODS=[
  // Proteins
  {name:'Chicken Breast (100g)',    cal:165,p:31,  c:0,  f:3.6},
  {name:'Chicken Thigh (100g)',     cal:209,p:26,  c:0,  f:11},
  {name:'Chicken Tikka (100g)',     cal:163,p:25,  c:5,  f:5},
  {name:'Butter Chicken (100g)',    cal:165,p:16,  c:8,  f:8},
  {name:'Mutton Curry (100g)',      cal:190,p:21,  c:4,  f:10},
  {name:'Buff Sukuti (100g)',       cal:280,p:34,  c:2,  f:14},
  {name:'Mutton Sukuti (100g)',     cal:290,p:35,  c:2,  f:15},
  {name:'Fish Rohu (100g)',         cal:97, p:17,  c:0,  f:2.8},
  {name:'Fish Curry (100g)',        cal:140,p:18,  c:5,  f:6},
  {name:'Eggs (1 whole)',           cal:78, p:6,   c:0.6,f:5},
  {name:'Egg White (1)',            cal:17, p:3.6, c:0.2,f:0.1},
  {name:'Egg Curry (1 egg)',        cal:130,p:8,   c:5,  f:9},
  {name:'Paneer (100g)',            cal:265,p:18,  c:3,  f:20},
  {name:'Palak Paneer (100g)',      cal:150,p:7,   c:8,  f:10},
  {name:'Paneer Bhurji (100g)',     cal:220,p:14,  c:6,  f:16},
  {name:'Soya Chunks (100g dry)',   cal:345,p:52,  c:26, f:0.5},
  {name:'Whey Protein (1 scoop)',   cal:120,p:24,  c:3,  f:1.5},
  {name:'Protein Bar (1)',          cal:200,p:20,  c:22, f:7},
  // Dairy
  {name:'Milk (200ml)',             cal:122,p:6.4, c:9.6,f:4.8},
  {name:'Curd / Dahi (100g)',       cal:98, p:11,  c:3.4,f:4.3},
  {name:'Greek Yogurt (100g)',      cal:59, p:10,  c:3.6,f:0.4},
  {name:'Lassi Sweet (200ml)',      cal:180,p:5,   c:32, f:4},
  {name:'Lassi Salty (200ml)',      cal:120,p:5,   c:16, f:4},
  {name:'Masala Chai (1 cup)',      cal:80, p:2,   c:14, f:2},
  // Grains / Staples
  {name:'Brown Rice (100g cooked)', cal:112,p:2.6, c:24, f:0.9},
  {name:'White Rice (100g cooked)', cal:130,p:2.7, c:28, f:0.3},
  {name:'Roti / Chapati (1)',       cal:104,p:3,   c:20, f:1.5},
  {name:'Paratha (1 plain)',        cal:180,p:4,   c:26, f:7},
  {name:'Aloo Paratha (1)',         cal:265,p:5,   c:38, f:10},
  {name:'Puri (1 piece)',           cal:110,p:2,   c:15, f:5},
  {name:'Oats (100g dry)',          cal:389,p:17,  c:66, f:7},
  {name:'Chiura / Beaten Rice (100g)',cal:346,p:7, c:77, f:1},
  {name:'Sattu (100g)',             cal:406,p:22,  c:65, f:7},
  {name:'Dhido (100g cooked)',      cal:142,p:3,   c:31, f:1},
  {name:'Sel Roti (1 piece)',       cal:180,p:3,   c:32, f:5},
  {name:'Poha (100g cooked)',       cal:158,p:3,   c:34, f:2},
  {name:'Upma (100g cooked)',       cal:135,p:3,   c:24, f:3},
  {name:'Khichdi (100g cooked)',    cal:110,p:4,   c:20, f:2},
  {name:'Dosa (1 plain)',           cal:133,p:3,   c:26, f:2},
  {name:'Idli (1)',                 cal:39, p:1.9, c:8,  f:0.2},
  // Dal / Lentils
  {name:'Dal / Lentils (100g)',     cal:116,p:9,   c:20, f:0.4},
  {name:'Dal Tadka (100ml)',        cal:80, p:4,   c:12, f:2},
  {name:'Sambar (100ml)',           cal:55, p:3,   c:8,  f:1},
  {name:'Rajma (100g cooked)',      cal:127,p:8.7, c:22, f:0.5},
  {name:'Chana / Chickpeas (100g)', cal:164,p:9,   c:27, f:2.6},
  {name:'Chole Bhature (1 plate)',  cal:490,p:13,  c:68, f:18},
  {name:'Kwati / Mixed Beans (100g)',cal:180,p:10, c:28, f:4},
  // Nepali Dishes
  {name:'Dal Bhat Set (1 plate)',   cal:450,p:15,  c:80, f:8},
  {name:'Chicken Momo (6 pcs)',     cal:260,p:18,  c:28, f:7},
  {name:'Buff Momo (6 pcs)',        cal:280,p:16,  c:30, f:8},
  {name:'Veg Momo (6 pcs)',         cal:210,p:8,   c:32, f:5},
  {name:'Thukpa (1 bowl)',          cal:320,p:14,  c:48, f:7},
  {name:'Aloo Tama (100g)',         cal:95, p:4,   c:16, f:2},
  {name:'Gundruk (100g)',           cal:240,p:26,  c:32, f:4},
  {name:'Yomari (1 piece)',         cal:180,p:4,   c:36, f:3},
  {name:'Newari Khaja Set',         cal:480,p:18,  c:62, f:16},
  {name:'Buff Choila (100g)',       cal:220,p:22,  c:3,  f:13},
  {name:'Chicken Biryani (1 plate)',cal:450,p:25,  c:52, f:14},
  {name:'Fried Rice (100g)',        cal:163,p:4,   c:28, f:4},
  // Vegetables & Others
  {name:'Sweet Potato (100g)',      cal:86, p:1.6, c:20, f:0.1},
  {name:'Potato (100g boiled)',     cal:87, p:1.9, c:20, f:0.1},
  {name:'Broccoli (100g)',          cal:34, p:2.8, c:7,  f:0.4},
  {name:'Spinach (100g)',           cal:23, p:2.9, c:3.6,f:0.4},
  {name:'Banana (1 medium)',        cal:89, p:1.1, c:23, f:0.3},
  {name:'Apple (1 medium)',         cal:95, p:0.5, c:25, f:0.3},
  {name:'Peanut Butter (1 tbsp)',   cal:94, p:4,   c:3,  f:8},
  {name:'Almonds (10 nuts)',        cal:69, p:2.5, c:2.4,f:6},
  {name:'Olive Oil (1 tbsp)',       cal:119,p:0,   c:0,  f:14},
  {name:'Samosa (1 piece)',         cal:145,p:3,   c:20, f:6},
  {name:'Pav Bhaji (1 plate)',      cal:400,p:10,  c:58, f:14},
];
  FT.register('catalog',{WEEKDAYS,WD_LABELS,MUSCLE_GROUPS,SEED_EXERCISES,SEED_PLANS,FOODS});
})();
