/* FitTrack Pro v15 — Workout Intelligence 3.0 domain utilities. */
(function(){
  const FT=window.FitTrack=window.FitTrack||{};
  const SET_TYPES={warmup:{label:'Warm-up',short:'WU',rest:45},working:{label:'Working',short:'WORK',rest:90},drop:{label:'Drop',short:'DROP',rest:60},failure:{label:'Failure',short:'FAIL',rest:120}};
  const PLATES=[25,20,15,10,5,2.5,1.25];
  const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
  function normalizeSetType(v){const x=String(v||'working').toLowerCase();return SET_TYPES[x]?x:'working';}
  function restForSet(set,prefs={}){if(prefs.autoRest===false)return 0;const t=normalizeSetType(set?.type);const override=Number(prefs?.restOverrides?.[t]);if(Number.isFinite(override)&&override>=15)return clamp(override,15,1800);return t==='working'&&prefs.defaultRest?clamp(Number(prefs.defaultRest),15,1800):(SET_TYPES[t]?.rest||90);}
  function parseRepRange(raw){const s=String(raw||'').replace(/\s/g,'');const m=s.match(/(\d+)\D+(\d+)/);if(m)return{min:Number(m[1]),max:Number(m[2])};const n=s.match(/\d+/);const v=n?Number(n[0]):0;return{min:v,max:v};}
  function progression(prev,targetReps,currentRpe){if(!prev)return{kind:'baseline',label:'Build baseline',detail:'No previous load recorded'};const w=Number(prev.weight),r=Number(prev.reps),range=parseRepRange(targetReps);if(range.max&&r>=range.max&&(currentRpe==null||currentRpe<=8))return{kind:'increase',delta:2.5,label:'+2.5 kg next time',detail:`${r} reps reached the top of the target range`};if(range.min&&r<range.min)return{kind:'hold',delta:0,label:'Keep the load',detail:`Build toward ${range.min} reps before increasing`};return{kind:'hold',delta:0,label:'Repeat / refine',detail:`Stay near ${range.min||range.max}–${range.max} reps`};}
  function sessionStats(session){const sets=Object.values(session?.setLogs||{}).flat(),done=sets.filter(s=>s.done),working=done.filter(s=>normalizeSetType(s.type)==='working'),volume=done.reduce((n,s)=>n+(Number(s.weight)||0)*(Number(s.reps)||0),0),rpes=done.map(s=>Number(s.rpe)).filter(n=>n>=1&&n<=10),prs=done.filter(s=>s._potentialPR).length;return{total:sets.length,done:done.length,pct:sets.length?Math.round(done.length/sets.length*100):0,volume:Math.round(volume),workingSets:working.length,avgRpe:rpes.length?Math.round(rpes.reduce((a,b)=>a+b,0)/rpes.length*10)/10:null,potentialPRs:prs};}
  function plateBreakdown(targetWeight,barWeight=20){const target=Number(targetWeight),bar=Number(barWeight)||20;if(!Number.isFinite(target)||target<=0)return{target:0,bar,side:0,pairs:[],possible:false,delta:0};const usable=target-bar;if(usable<0)return{target,bar,side:0,pairs:[],possible:false,delta:Math.abs(usable)};let side=usable/2;const pairs=[];for(const plate of PLATES){const count=Math.floor((side+1e-9)/plate);if(count){pairs.push({plate,count});side=Math.round((side-count*plate)*100)/100;}}return{target,bar,side:Math.round((usable/2-side)*100)/100,pairs,possible:side<0.001,delta:Math.round(side*2*100)/100};}
  function nextExerciseIndex(setLogs,current){return Object.keys(setLogs||{}).map(Number).filter(n=>Number.isFinite(n)&&n>current).sort((a,b)=>a-b)[0]??null;}
  FT.register('workoutIntelligence',{SET_TYPES,normalizeSetType,restForSet,progression,sessionStats,plateBreakdown,nextExerciseIndex});
})();
